[package]
name = "mupc-intercore"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
tokio.workspace = true
tracing.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
byteorder = "1.5"
tokio-modbus = "0.13"
tokio-serial = "5.4"
chrono = { workspace = true }
mupc-common = { path = "../common" }
mupc-core = { path = "../core" }

[dev-dependencies]
tokio-test = "0.4"