[package]
name = "mupc-data-processing"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
tokio.workspace = true
tracing.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
async-trait = "0.1"
thiserror.workspace = true
mupc-common = { path = "../common" }
mupc-mqtt-bridge = { path = "../mqtt-bridge" }
rusqlite = "0.32"
chrono.workspace = true

[dev-dependencies]
tokio-test = "0.4"